In [18]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [19]:
df = pd.read_csv('custom_multi_year_diabetes_dataset.csv')

In [20]:
df.head()

,Age,Gender,BMI,Systolic_BP,Diastolic_BP,HbA1c_Level,Diabetes_Status,Source_Year
0,69.0,Male,26.7,122.0,72.0,13.9,2,2013-2014
1,54.0,Male,28.6,156.0,62.0,9.1,2,2013-2014
2,72.0,Male,28.9,140.0,90.0,8.9,2,2013-2014
3,73.0,Female,19.7,136.0,86.0,4.9,0,2013-2014
4,56.0,Male,41.7,160.0,84.0,5.5,0,2013-2014

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20111 entries, 0 to 20110
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              20111 non-null  float64
 1   Gender           20111 non-null  str
 2   BMI              19834 non-null  float64
 3   Systolic_BP      18409 non-null  float64
 4   Diastolic_BP     18409 non-null  float64
 5   HbA1c_Level      19001 non-null  float64
 6   Diabetes_Status  20111 non-null  int64
 7   Source_Year      20111 non-null  str
dtypes: float64(5), int64(1), str(2)
memory usage: 1.5 MB

In [22]:
df.shape

(20111, 8)

In [23]:
df.drop(columns=['Gender', 'Source_Year'], inplace= True)

In [24]:
df.head()

    Age   BMI  Systolic_BP  Diastolic_BP  HbA1c_Level  Diabetes_Status
0  69.0  26.7        122.0          72.0         13.9                2
1  54.0  28.6        156.0          62.0          9.1                2
2  72.0  28.9        140.0          90.0          8.9                2
3  73.0  19.7        136.0          86.0          4.9                0
4  56.0  41.7        160.0          84.0          5.5                0

In [25]:
df.isnull().sum()

Age                   0
BMI                 277
Systolic_BP        1702
Diastolic_BP       1702
HbA1c_Level        1110
Diabetes_Status       0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(12)

In [27]:
df.drop_duplicates(df, inplace= True)

In [28]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.dropna(subset= ['Systolic_BP', 'Diastolic_BP', 'HbA1c_Level', 'BMI'], inplace= True)

In [35]:
df.isnull().sum()

Age                0
BMI                0
Systolic_BP        0
Diastolic_BP       0
HbA1c_Level        0
Diabetes_Status    0
dtype: int64