Credit Card Customer Churn Prediction

In [73]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [74]:
df = pd.read_csv('Churn_Modelling.csv')

In [75]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [76]:
df.shape

(10000, 14)

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.2 MB

In [78]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [79]:
df.duplicated().sum()

np.int64(0)

In [80]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [81]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [82]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [83]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace= True)

In [84]:
df.shape

(10000, 11)

In [85]:
df['Gender'] = df['Gender'].map({
    'Male': 1,
    'Female': 0
})

In [86]:
df = pd.get_dummies(
    df,
    columns= ['Geography'],
    drop_first= True,
    dtype= int
)

In [87]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0,1

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
X = df.drop(columns=['Exited'])
y = df['Exited']

In [90]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size= 0.2,
    random_state= 1
)

In [91]:
X_train.shape

(8000, 11)

In [92]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [93]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [94]:
import tensorflow as tf
from tensorflow import keras 
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [96]:
model = Sequential()

In [97]:
model.add(Dense(3,activation= 'sigmoid', input_dim = 11))
model.add(Dense(1, activation= 'sigmoid'))

In [99]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [100]:
model.compile(loss = 'binary_crossentropy', optimizer= 'Adam')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [101]:
model.fit(X_train_scaled, y_train, epochs= 10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 967us/step - loss: 0.5898
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 0.5018
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - loss: 0.4702
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - loss: 0.4562
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - loss: 0.4476
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - loss: 0.4416
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 0.4371
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - loss: 0.4338
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - loss: 0.4313
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4295

In [104]:
y_log = model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step

In [106]:
y_pred = np.where(y_log> 0.5, 1,0)

In [107]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.808